name: Controller Docker Image CI

on:
  push:
    paths:
      - 'AlcorController/**'
      - '!AlcorController/docs/**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Alcor controller
      run: ./scripts/build.sh
      working-directory: ./AlcorController
    - name: Build docker image for Alcor Controller
      run: docker build . --file Dockerfile --tag alcor_controller:$(date +%s)
      working-directory: ./AlcorController